#!/usr/bin/env python3
"""
agents_to_cli.py — generate kiro-cli JSON agents from the Kiro IDE `.md` subagents.
Zero install: pure Python 3 (stdlib only). Same source, two runtimes.

WHY this exists
  The neo agents in `../agents/*.md` are authored in **Kiro IDE** subagent
  format (YAML frontmatter + markdown body). **kiro-cli** (the Amazon Q Developer
  CLI fork) does NOT read those — `kiro-cli agent list` only registers `*.json`
  agents (Amazon Q schema). So the IDE `.md` files are invisible to kiro-cli and
  delegation never fires. This script converts each `.md` → a kiro-cli `<name>.json`
  so the SAME `.md` source drives both runtimes. `~/.kiro/agents/` holds both:
  the IDE reads the `.md`, kiro-cli reads the `.json`; they don't collide.

WHAT it does per agent
  1. Parse the 5-key frontmatter (name/description/tools/includePowers/includeMcpJson).
  2. Map IDE tool names → kiro-cli canonical (`write`→`fs_write`, `subagent`→`use_subagent`;
     read/glob/grep/shell unchanged). `includePowers` is dropped (not in the kiro-cli schema).
  3. Put the whole markdown body into `prompt`, PREPENDED with a generated
     CLI-runtime preamble that binds the IDE dispatch language ("Use the {role}
     subagent to …") to the real `use_subagent` tool. The body is NOT edited —
     the preamble is append-only and absent from the source `.md` (so the IDE is
     unaffected). The orchestrator gets an extra delegation contract.

Usage
  python3 agents_to_cli.py --out DIR [--src DIR]
  python3 agents_to_cli.py --check [--src DIR]        # dry-run: parse+map, write nothing
    --src   dir of *.md agents     (default: ../agents next to this script)
    --out   dir to write <name>.json into  (required unless --check)
    --check  dry-run; exit non-zero on any parse/convert error (lets setup.sh fail fast)
Exit code: 0 = all converted clean, 1 = at least one agent failed.
"""
import argparse, json, sys, pathlib

# The sole delegating agent: only this one receives ORCHESTRATOR_PREAMBLE (the
# use_subagent dispatch contract). Renaming the orchestrator file, or adding
# another agent that delegates, means updating this name AND the matching branch
# in build_agent() — the coupling is intentional but load-bearing.
ORCHESTRATOR = "neo-orchestrator"

# IDE tool name -> kiro-cli canonical. Names not listed pass through unchanged
# (read/glob/grep/shell are already valid kiro-cli tool names). `kiro-cli agent
# validate` is the final arbiter on tool validity.
TOOL_MAP = {"write": "fs_write", "subagent": "use_subagent"}

# --- generated CLI-runtime preamble (NOT present in the source .md) ----------
SHARED_PREAMBLE = """\
<!-- ⚙️ kiro-cli runtime preamble — generated by agents_to_cli.py; NOT in the source .md. The Kiro IDE reads the .md without this block. -->

> **Runtime: kiro-cli.** You are running as a kiro-cli JSON agent, not inside the Kiro IDE. Two bindings apply to every instruction in this prompt:
>
> 1. **Paths with `~` work.** When told to read a reference or steering file by a path like `~/.kiro/skills/neo/references/phase-map.md`, or to glob `~/.kiro/steering/*.md`, call your `read` / `glob` tool with that exact path — `~` expands to the user's home directory.
> 2. **"Use the {role} subagent to …" / "/{role} …" is NOT chat text — it means call the `use_subagent` tool.** Wherever an instruction below says to dispatch, invoke, or "Use the {name} subagent to {task}" (or shows the slash form `/{name}`), perform it as a real `use_subagent` tool call (`agent_name: "{name}"`, `query: <the task>`). Printing that sentence as a message does nothing on kiro-cli. Only the orchestrator delegates; specialists do their own work and never call `use_subagent`."""

ORCHESTRATOR_PREAMBLE = """\
>
> **Delegation contract (orchestrator only).** Your whole job is routing via the `use_subagent` tool. Every dispatch in the flow below — the Delegation Protocol, the Prompt Composition Template (`Use the {specialist-name} subagent to: …`), and any `/{specialist-name}` form — is executed as a `use_subagent` call:
> - `agent_name` = one of `librarian`, `business-analyst`, `architect`, `qa`, `developer`, `code-reviewer`, `security`, `system-analyzer`
> - `query` = the fully-composed prompt from your Prompt Composition Template (Task / Inputs / Expected Outputs / Context from Prior Specialists)
> - `relevant_context` = the prior artifacts and file paths you would otherwise paste
> NEVER emit "Use the X subagent to …" as a chat message and stop — that is the #1 failure mode on kiro-cli (the turn ends and nothing runs). It MUST be a tool call.
>
> **Parallel cap:** kiro-cli allows at most **4** subagents per turn. Your only parallel batch is the **Verify phase — Code Reviewer ∥ Security ∥ QA-E2E** (3 calls in one turn) — safe. Everything else is sequential: one `use_subagent`, read its result, checkpoint, then the next.
>
> **Checkpoints & interaction:** the four checkpoints (**CP1** plan / **CP2** BA5-intent / **CP3** pre-Build / **CP-final**) are plain-text numbered questions to the user.
> - **Interactive REPL** (default `kiro-cli chat`): present them exactly as written and wait for the user's next turn — this works as designed.
> - **`--no-interactive`** (no user to answer): do NOT stall. State up front that checkpoints will auto-proceed on the **Recommended** option, run the whole plan, then emit ONE consolidated report (plan + every role's result + each checkpoint recorded as `auto-proceeded: <option>` + Pre-Finalization Checklist + Final Summary). Never drop a checkpoint silently. A genuine `BLOCKED` / Open-Question that needs a *user decision* (GATE 6 / Never-Guess) still halts the run under a clear **"⛔ NEEDS USER INPUT"** heading instead of guessing."""


def parse_frontmatter(text):
    """Return (meta dict, body str). Raises ValueError on malformed frontmatter.
    The frontmatter is a fixed 5-key `key: scalar` block fenced by `---` lines —
    no YAML features beyond that and one inline JSON-style array, so a tiny hand
    parser is correct here (PyYAML intentionally avoided: not a stdlib dep)."""
    lines = text.split("\n")
    if not lines or lines[0].strip() != "---":
        raise ValueError("missing opening '---' frontmatter fence on line 1")
    close = next((i for i in range(1, len(lines)) if lines[i].strip() == "---"), None)
    if close is None:
        raise ValueError("missing closing '---' frontmatter fence")
    meta = {}
    for ln in lines[1:close]:
        if not ln.strip():
            continue
        if ":" not in ln:
            raise ValueError(f"frontmatter line has no ':' -> {ln!r}")
        key, _, val = ln.partition(":")
        meta[key.strip()] = val.strip()
    body = "\n".join(lines[close + 1:])
    return meta, body


def map_tools(raw):
    """Map IDE tool names to kiro-cli canonical, preserving order, de-duped."""
    out = []
    for t in raw:
        m = TOOL_MAP.get(t, t)
        if m not in out:
            out.append(m)
    return out


def build_agent(name, meta, body):
    """Assemble the kiro-cli agent JSON object from one parsed `.md`."""
    if "tools" not in meta:
        raise ValueError("frontmatter missing 'tools'")
    try:
        raw_tools = json.loads(meta["tools"])
    except json.JSONDecodeError as e:
        raise ValueError(f"cannot parse tools array {meta['tools']!r}: {e}")
    if not isinstance(raw_tools, list):
        raise ValueError(f"'tools' is not a list: {meta['tools']!r}")
    tools = map_tools(raw_tools)

    preamble = SHARED_PREAMBLE
    if name == ORCHESTRATOR:
        preamble += "\n" + ORCHESTRATOR_PREAMBLE
    prompt = preamble + "\n\n" + body

    return {
        "name": name,
        "description": meta.get("description", ""),
        "prompt": prompt,
        "mcpServers": {},
        "tools": tools,
        "toolAliases": {},
        "allowedTools": [],
        "resources": [],
        "hooks": {},
        "toolsSettings": {},
        "includeMcpJson": meta.get("includeMcpJson", "false").lower() == "true",
        "model": None,
    }


def main():
    here = pathlib.Path(__file__).resolve().parent
    ap = argparse.ArgumentParser(description="Generate kiro-cli JSON agents from Kiro IDE .md subagents.")
    ap.add_argument("--src", default=str(here.parent / "agents"),
                    help="dir of *.md agents (default: ../agents next to this script)")
    ap.add_argument("--out", help="dir to write <name>.json into (required unless --check)")
    ap.add_argument("--check", action="store_true",
                    help="dry-run: parse+map+build, write nothing, non-zero exit on any error")
    args = ap.parse_args()

    if not args.check and not args.out:
        ap.error("--out is required unless --check is given")

    src = pathlib.Path(args.src)
    if not src.is_dir():
        print(f"ERROR: --src is not a directory: {src}", file=sys.stderr)
        sys.exit(2)
    files = sorted(src.glob("*.md"))
    if not files:
        print(f"ERROR: no *.md agents found under {src}", file=sys.stderr)
        sys.exit(2)

    out_dir = pathlib.Path(args.out) if args.out else None
    if out_dir and not args.check:
        out_dir.mkdir(parents=True, exist_ok=True)

    errors = 0
    for f in files:
        try:
            meta, body = parse_frontmatter(f.read_text(encoding="utf-8"))
            name = meta.get("name", "").strip()
            if not name:
                raise ValueError("frontmatter missing 'name'")
            if name != f.stem:
                # not fatal — name drives the json filename — but worth surfacing
                print(f"    warn   {f.name}: frontmatter name '{name}' != filename stem '{f.stem}'")
            obj = build_agent(name, meta, body)
            if args.check:
                print(f"✓ {f.name:24} → {name}.json  OK  [{', '.join(obj['tools'])}]")
            else:
                dest = out_dir / f"{name}.json"
                dest.write_text(json.dumps(obj, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
                print(f"✓ {f.name:24} → {dest.name}  [{', '.join(obj['tools'])}]")
        except (ValueError, OSError) as e:
            errors += 1
            print(f"✗ {f.name:24} ERROR: {e}")

    mode = "checked" if args.check else "wrote"
    print(f"\n{'FAILED' if errors else 'PASS'} — {mode} {len(files) - errors}/{len(files)} agent(s), {errors} error(s)")
    sys.exit(1 if errors else 0)


if __name__ == "__main__":
    main()
