logger:
  environment: development
  level: info

service:
  host: 0.0.0.0
  port: 8080
  service_id: NEOSVC
  shutdown_timeout: 10s

postgres:
  host: postgres
  port: 5432
  user: postgres
  password: password
  database: sit_core
  sslmode: disable
  schema: neoschema

redis:
  host: valkey
  port: 6379
  username:
  password: password
  database: 0
  use_tls: false

kafka:
  enabled: false
  address: kafka:19092
  use_aws_profile: false
